service: test-svc
provider:
  name: aws

functions:
  hello:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    # or `{cargo-package-name}` for short when you are building a
    # default bin for a given package.
    handler: hello
    events:
      - alb:
          listeners: 'somearn'
          path: '/'

plugins:
 - serverless-aws-alb